service: humor-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  preverHumor:
    handler: src/handlers/humor.preverHumor
    events:
      - httpApi:
          path: /humor
          method: get

plugins:
  - serverless-offline

package:
  patterns:
    - "!node_modules/**"
    - "dist/**"